### ISSUE TITLE
npm安装的问题

### ISSUE THREAD

**Issue by jyk1987** [RNCommon/react-native-easemob#1]
你好,我在 npm 下载的react-native-easemob不是你这个啊,并且 npm 里面没有react-native-hecom-easemob

**Comment by gxsshallot** [comment]
@jyk1987 你好，这个还没有发布到npm上，目前还在开发中。。未来发布是准备使用react-native-hecom-easemob的名字。

**Comment by jyk1987** [comment]
哦好的,谢谢你们的开发啊,现在环信在 rn 下使用是个问题.请问下,大概什么时候能发布?非常期待你们早日发布

**Comment by gxsshallot** [comment]
@jyk1987 这个不太确定，大概8、9月份的。

**Comment by jyk1987** [comment]
@gaoxiaosong 你好,我已经手动把代码集成到项目中了.期待你们正式发布

**Comment by gxsshallot** [comment]
@jyk1987 已经发布了，库名改为`react-native-im-easemob`，现在是v1.0.0版本。
