### ISSUE TITLE
ios 使用过程中接收消息崩溃。源于对模型转换字典的时候

### ISSUE THREAD

**Issue by CYZZ** [RNCommon/react-native-easemob#3]
在NSObject+Util中的 - (NSDictionary *)objectToDictionary方法进行模型转字典，如果消息是文本类型未能在基类EMMessage中的body属性（EMMessageBody）找到对应的属性。导致解析失败；
后来我使用了YYModel没有崩溃但是不能正确解析body里的数据。

**Comment by gxsshallot** [comment]
@CYZZ 你是`mj_keyValuesWithIgnoredKeys`这个方法找不到么？我说明里忘写了，这个库用到的MJExtension需要定制版的，Podfile里面如下安装：

```
pod 'MJExtension', :git => 'https://github.com/RNCommon/MJExtension.git', :commit => 'cd3de71c4955935a762a46e59d90160991f5fa92'
```

这个MJExtension增加了黑名单功能，屏蔽掉了EMMessage里面的一些属性：`@"coreObject",@"impl",@"coreBody",@"superclass",@"debugDescription"`

**Comment by CYZZ** [comment]
哦哦，排查到了，是模型的属性如果是另一个模型的话，没有忽略ignore的键值。但是不明白，使用runtime遍历获取的所有key,为什么使用KVC的valueforkey:的时候会找不到对应的key呢？

**Comment by gxsshallot** [comment]
@CYZZ 我也不明白，这个只能问环信了，不知道他们类的内部是怎么写的。。所以只能看哪些崩了就忽略掉。稍后会修改一下README和example工程，好久没更新这俩了。
