### ISSUE TITLE
找不到example文件啊。而且yarn

### ISSUE THREAD

**Issue by ZakZheng** [RNCommon/react-native-easemob#9]
![image](https://user-images.githubusercontent.com/29496477/59732210-e90bad00-927b-11e9-9748-0bdc17ece599.png)
下载下来就只有这些文件，没看到有example文件，不知道该怎么集成

**Comment by summer88123** [comment]
这个库主要就是环信API的RN封装，如何添加到项目中可以参考Readme，具体接口调用可以参考环信的文档，API名称基本都和环信保持了一致。主要流程就是init，设置各种事件监听，login

**Comment by summer88123** [comment]
@ZakZheng 这个库主要就是环信API的RN封装，如何添加到项目中可以参考Readme，具体接口调用可以参考环信的文档，API名称基本都和环信保持了一致。主要流程就是init，设置各种事件监听，login
